language: ruby
addons:
  postgresql: "9.3"
  firefox: "45.4.0esr"
services:
  - postgresql
  - xvfb
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - sudo service postgresql restart 9.3
  - gem install bundler
  - gem list -a
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
