default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: payroll_development

test: &test
  <<: *default
  database: payroll_test

production:
  <<: *default
  database: payroll_production
  username: payroll
  password: <%= ENV['PAYROLL_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
